//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NursingCollegeDBEntities : DbContext
    {
        public NursingCollegeDBEntities()
            : base("name=NursingCollegeDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Attendance> Attendances { get; set; }
        public virtual DbSet<AttendanceSheet> AttendanceSheets { get; set; }
        public virtual DbSet<ClassInfo> ClassInfoes { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Reply> Replies { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<Slider> Sliders { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudyMaterial> StudyMaterials { get; set; }
        public virtual DbSet<StudyMaterialFile> StudyMaterialFiles { get; set; }
        public virtual DbSet<SubjectAllocation> SubjectAllocations { get; set; }
        public virtual DbSet<Subject> Subjects { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
    }
}
