//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyMaterial
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyMaterial()
        {
            this.StudyMaterialFiles = new HashSet<StudyMaterialFile>();
        }
    
        public int Id { get; set; }
        public string Topic { get; set; }
        public string Description { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<long> UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyMaterialFile> StudyMaterialFiles { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
