//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
       
        public Attendance()
        {
            this.AttendanceSheets = new HashSet<AttendanceSheet>();
        }
    
        public long Id { get; set; }
        
        public Nullable<int> SubjectId { get; set; }
        public Nullable<long> StudentId { get; set; }        
        public virtual ICollection<AttendanceSheet> AttendanceSheets { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
