//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Department
    {
        
        public Department()
        {
            this.Subjects = new HashSet<Subject>();
            this.UserAccounts = new HashSet<UserAccount>();
        }
    
        public int Id { get; set; }
        [Required,Display(Name ="Department")]
        public string DeptName { get; set; }
    
        
        public virtual ICollection<Subject> Subjects { get; set; }
        
        public virtual ICollection<UserAccount> UserAccounts { get; set; }
    }
}
