//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reply
    {
        public long Id { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> ReplyDate { get; set; }
        public Nullable<long> CommentId { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual UserAccount UserAccount { get; set; }
    }
}
