//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Slider
    {
        public int Id { get; set; }
        [Required]
        public string Caption { get; set; }
        [Display(Name = "Select Image")]
        public string ImagePath { get; set; }
        public Nullable<bool> IsActive { get; set; }
       
        [DataType(DataType.MultilineText)]
        [Required]
        public string Description { get; set; }
        public HttpPostedFileBase File { get; set; }

    }
}
