//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class UserAccount
    {
        public long Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Parentage { get; set; }
        public string Gender { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> DOB { get; set; }
        [Required]
        public string Address { get; set; }
        [Required,DataType(DataType.PhoneNumber)]
        public string ContactNo { get; set; }
        [Required,DataType(DataType.EmailAddress), RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$", ErrorMessage = "Enter Valid Email")]
        public string Email { get; set; }
        public string ImagePath { get; set; }
        [Required,Display(Name ="Department")]
        public Nullable<int> DepartmentId { get; set; }
     [DataType(DataType.Password)]
        public string Password { get; set; }
        public string Salt { get; set; }
        public string ResetCode { get; set; }
        [Required]
        public string UserRole { get; set; }
        public Nullable<bool> IsActive { get; set; }
        [Required]
        public string UserCode { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Student Student { get; set; }

        [NotMapped]
        public HttpPostedFileBase FileUpload { get; set; }

       
        public virtual ICollection<StudyMaterial> StudyMaterials { get; set; }
        
        public virtual ICollection<Comment> Comments { get; set; }
        
        public virtual ICollection<Reply> Replies { get; set; }
    }
}
